name:                ebook-metadata
synopsis:            Parse metadata from ebooks, e.g. EPUB
version:             0.0.1.0
github:              akirak/ebook-metadata
homepage:            https://github.com/akirak/ebook-metadata
license:             BSD3
author:              Akira Komamura
maintainer:          Akira Komamura
copyright:           Akira Komamura
category:            codec
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

default-extensions:
  - NoImplicitPrelude
  - RecordWildCards
  - OverloadedStrings
  - PatternGuards

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - aeson
  - bytestring
  - text

library:
  source-dirs: src
  dependencies:
    - zip-archive
    - xml-conduit
    - containers

executables:
  ebook-metadata:
    main:            Main.hs
    source-dirs:     app
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
    dependencies:
      - ebook-metadata
      # - bytestring
      # - aeson

tests:
  ebook-metadata-tests:
    source-dirs:   test
    main:          Spec.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - ebook-metadata
      - hspec
