name:                epubinfo
synopsis:            Extract information from EPUB
version:             0.0.1.1
github:              akirak/epubinfo
homepage:            https://github.com/akirak/epubinfo
license:             BSD3
license-file:        LICENSE
author:              Akira Komamura
maintainer:          Akira Komamura
copyright:           Copyright (c) 2020-2021 Akira Komamura
category:            codec program
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

default-extensions:
  - NoImplicitPrelude
  - RecordWildCards
  - OverloadedStrings
  - PatternGuards

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - aeson
  - bytestring
  - text
  - exceptions

executables:
  epubinfo:
    main:            Main.hs
    source-dirs:     src
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
    dependencies:
      - zip-archive
      - xml-conduit
      - containers
      - optparse-simple
