name: Build executable
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths:
    - flake.nix
    - flake.lock
    - '**/*.hs'
jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
      # Explicitly check out a branch if called by a workflow_call event.
      # Otherwise, check out the default branch.
        ref: ${{ inputs.ref }}
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        skipPush: ${{ github.ref_name != 'master' }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Print the GHC version
      run: nix eval .#epubinfo.compiler.version
    - run: nix build
