name: 'CI'
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths:
    - flake.nix
    - flake.lock
    - '**/*.hs'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        skipPush: ${{ github.ref_name != 'master' }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Print the GHC version
      run: nix develop -c ghc --version
    - run: nix build
    - run: nix flake check
