name: Update the flake inputs

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - flake-update

jobs:
  update:
    runs-on: ubuntu-latest

    outputs:
      pr: ${{ steps.pr.outputs.pull-request-operation }}

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          flake-registry = https://raw.githubusercontent.com/akirak/flake-pins/master/registry.json

    - uses: DeterminateSystems/update-flake-lock@v15
      with:
        pr-title: "Update flake.lock"
        pr-labels: |
          automation
